### ISSUE TITLE
最新的2023.5.2版本，会报错

### ISSUE THREAD

**Issue by Seifon** [shaonianzhentan/updater#1]
看报错，好像是调用的ha接口被移除了

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/updater/__init__.py", line 11, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by Seifon** [comment]
和风天气插件也有类似的问题，望一起修复

**Comment by shaonianzhentan** [comment]
请使用其它的插件吧，这两个插件我不想更新了
